# Generated by Django 4.1.1 on 2022-10-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('othername', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, null=True)),
                ('schedule', models.BooleanField(default=False)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('personalize', models.BooleanField(default=False)),
                ('contacts', models.CharField(max_length=5000, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('description_type', models.CharField(max_length=100, null=True)),
                ('contact_group', models.CharField(max_length=150, null=True)),
                ('total_contacts', models.IntegerField(default=0, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_period', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('message_type', models.CharField(max_length=150, null=True)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('main_message', models.CharField(max_length=1000, null=True)),
                ('total_characters', models.IntegerField(default=0, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('web_message', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='image-uploads/')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='file-uploads/')),
                ('audio_file', models.FileField(blank=True, default='', null=True, upload_to='audio-uploads/')),
                ('sent_by', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, null=True)),
                ('unit_amount_usd', models.IntegerField(default=0, null=True)),
                ('unit_amount_ghs', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
