# Generated by Django 4.1.1 on 2022-10-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
