# Generated by Django 4.1.1 on 2022-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0003_credits_topups_post_branch_alter_post_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topups',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
