# Generated by Django 4.1.1 on 2022-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0004_topups_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypes',
            name='unit_amount_ghs',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servicetypes',
            name='unit_amount_usd',
            field=models.FloatField(default=0, null=True),
        ),
    ]
