# Generated by Django 4.1.1 on 2022-10-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0006_alter_topups_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='topups',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
