# Generated by Django 4.1.1 on 2022-10-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0007_topups_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
