# Generated by Django 4.1.1 on 2023-07-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0008_clientemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroups',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactgroups',
            name='client_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
